Bac 148 add pagination control
yw-liftandshift/backlog-poc-rewrite pull request #144
Opened 2024-04-02 19:42 UTC by nassery318

npm run build is working
docker build . is working

2024-04-02 19:49 UTC, marcusmonteirodesouza requested changes

2024-04-02 19:49 UTC, marcusmonteirodesouza commented on frontend/src/app/[locale]/submit/page.tsx
> +                aria-label='Click to upload your pdfs or Outlook msg files to Google Cloud Storage'
```suggestion
                aria-label='Click to upload your Outlook &apos;.msg&apos; files to Google Cloud Storage'
```

2024-04-02 19:49 UTC, marcusmonteirodesouza commented on frontend/src/app/[locale]/submit/page.tsx
> +              disabled={pageNumber * pageSize >= totalCount}
Maybe create a function that returns if it's the last page?

2024-04-02 19:49 UTC, marcusmonteirodesouza commented on frontend/src/app/[locale]/submit/page.tsx
> +              disabled={pageNumber === 1}
Maybe create a function to return if it's the first page?

2024-04-02 19:49 UTC, marcusmonteirodesouza commented on frontend/src/app/[locale]/submit/page.tsx
> +      console.log('the total count is:', totalCount);
Should this be removed?

2024-04-02 20:48 UTC, leechristensenYopp commented on frontend/src/app/[locale]/submit/page.tsx
> +              Next entries <MdArrowForward />
Don't forget to translate

2024-04-02 20:48 UTC, leechristensenYopp commented on frontend/src/app/[locale]/submit/page.tsx
> +              aria-label="Next Entries in the Table"
Don't forget to translate

2024-04-02 20:48 UTC, leechristensenYopp commented on frontend/src/app/[locale]/submit/page.tsx
> +              aria-label="Previous Entries in the Table"
Don't forget to translate

2024-04-02 20:48 UTC, leechristensenYopp commented on frontend/src/app/[locale]/submit/page.tsx
> +                    Click to upload your Outlook &apos;.msg&apos; files to
Don't forget to translate

2024-04-04 14:27 UTC, marcusmonteirodesouza approved these changes
LGTM!

2024-04-04 14:27 UTC, nassery318 reviewed
comments addressed

2024-04-04 14:32 UTC, nassery318 commented on frontend/src/app/[locale]/submit/page.tsx
> +                aria-label='Click to upload your pdfs or Outlook msg files to Google Cloud Storage'
Done!

2024-04-04 14:34 UTC, merged